version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - run: echo ${CIRCLE_WORKFLOW_ID}
      - run:
          name: Create cloudformation stack
          command: |
            aws cloudformation deploy \
              --stack-name ${CIRCLE_WORKFLOW_ID:0:7}-stack \
              --template-file exercises/cfn/ec2.yml \
              --parameter-overrides file://exercises/cfn/ec2-params.json \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["57:e4:e8:c3:d0:0b:18:b9:75:58:ed:dc:87:fa:18:fe"]
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Install ssh
          command: |
              apk add --update openssh-client
              eval $(ssh-agent -s)
              ssh-add <(echo "$SSH_PRIVATE_KEY")
      - run:
          name: Run playbook and configure server
          command: |
            cd exercises
            ansible-playbook -i inventory.txt main-remote.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run: |
          if curl -s --head "https://blog.udacity.com/"
          then
            return 0
          else
            return 1
          fi

workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      # - smoke_test
