version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - run: echo ${CIRCLE_WORKFLOW_ID}
      - run:
          command: !
            aws cloudformation deploy \
              --stack-name ${CIRCLE_WORKFLOW_ID:0:5}-stack \
              --template-file exercises/ec2.yml \
              --parameters exercises/ec2-params.yml \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
